#!/bin/bash

TRIPLE=arm-none-linux-gnueabihf
GCC=/usr/magrang/sysroots/gcc-arm-10.2-2020.11-x86_64-$TRIPLE

clang \
  -target $TRIPLE \
  -march=armv7-a \
  --sysroot=$GCC/$TRIPLE/libc \
  --gcc-toolchain=$GCC \
  "$@"
