#!/bin/bash

TRIPLE=arm-none-linux-gnueabihf
GCC=/usr/magrang/sysroots/gcc-arm-10.2-2020.11-mingw-w64-i686-$TRIPLE
VERSION=10.2.1

clang++ \
  -target $TRIPLE \
  -march=armv7-a \
  -isystem $GCC/$TRIPLE/include/c++/$VERSION \
  -isystem $GCC/$TRIPLE/include/c++/$VERSION/$TRIPLE \
  -isystem $GCC/$TRIPLE/include/c++/$VERSION/backward \
  --sysroot=$GCC/$TRIPLE/libc \
  --gcc-toolchain=$GCC \
  "$@"
